<<<<<<< HEAD
=======
version: '3.8'

>>>>>>> 42956b651617e0d39d431bbe3a766d6d833c76e4
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
<<<<<<< HEAD
    container_name: laravel-blog-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - laravel-blog
    depends_on:
      - db

  webserver:
    image: nginx:alpine
    container_name: laravel-blog-webserver
=======
    container_name: laravel_app
>>>>>>> 42956b651617e0d39d431bbe3a766d6d833c76e4
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
<<<<<<< HEAD
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - laravel-blog
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: laravel-blog-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel_blog
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_PASSWORD: user_password
      MYSQL_USER: laravel_user
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - laravel-blog

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: laravel-blog-phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports:
      - "8080:80"
    networks:
      - laravel-blog
    depends_on:
      - db

networks:
  laravel-blog:
    driver: bridge

volumes:
  dbdata:
    driver: local
=======
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=laravel_db
      - DB_USERNAME=root
      - DB_PASSWORD=rootpassword
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: laravel_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: laravel_db
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:

>>>>>>> 42956b651617e0d39d431bbe3a766d6d833c76e4
